### ISSUE TITLE
Jakt cheatsheet todo list

### ISSUE THREAD

**Issue by Optimoos** [Optimoos/jakt#2]
Things left to mention in the sections modified so far:
## Imports

- [ ] `import comptime_fn()`

## Literals

- [x] Tuples

- [x] Arrays

- [x] Dictionaries

- [x] Sets

- [x] Strings (+overloaded strings?)

## Declarations

- [x] Structs

- [x] Classes

- [x] Namespaces

- [x] Traits

- [ ] External trait implementations

- [ ] `forall<>`-style decls

## Control flow

- [x] `guard`

- [x] `match`

- [x] `try` (both expression and statement forms)

- [x] `continue`

## Functions

- [x] Comptime functions

- [ ] Methods?

- [ ] Return type inference conditions?
